CREATE TABLE `usr` (
  `name` varchar(45) CHARACTER SET utf8 DEFAULT '' COMMENT '회원 닉네임',
  `gender` varchar(11) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '회원 성별',
  `birthDate` int(11) DEFAULT NULL COMMENT '회원 생일',
  `age` int(11) DEFAULT NULL COMMENT '회원 나이',
  `email` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '회원 메일주소',
  `passwd` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '회원 비밀번호',
  `kind_sns` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'sns 종류',
  `firebaseToken` longtext COLLATE utf8_unicode_ci NOT NULL COMMENT 'sns token',
  `firebaseSession` varchar(225) COLLATE utf8_unicode_ci DEFAULT '' COMMENT 'sns token',
  `schedule` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '여행기간',
  `memberCount` int(11) DEFAULT NULL COMMENT '원하는 동행 수',
  `uid` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'firebaseuid',
  `answer` json DEFAULT NULL,
  `id` int(100) unsigned NOT NULL AUTO_INCREMENT COMMENT '고유 id [서버로 쏴줄 때 uid랑 firebasetoken으로 primarly key 써서 주면 문제가 됨으로]',
  `destination` int(11) DEFAULT NULL COMMENT '여행 도시',
  `country` int(11) DEFAULT NULL COMMENT '본인 국적',
  `minDate` int(11) DEFAULT NULL COMMENT '여행 첫날',
  `maxDate` int(11) DEFAULT NULL COMMENT '여행 마지막날',
  `minAge` int(11) DEFAULT NULL COMMENT '원하는 최소 나이',
  `maxAge` int(11) DEFAULT NULL COMMENT '원하는 최대 나이',
  `preferenceGender` int(11) DEFAULT NULL COMMENT '선호 성별',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
